### ISSUE TITLE
Ip's are not logging however credentials are

### ISSUE THREAD

**Issue by tuffboy807** [sky9262/phishEye#1]
So the only issue is that the ip and information associated with the ip is either not logging or just not showing up, it doesn't give me any errors and I recloned it just in case
all I am getting is(was testing to see if it would log it after I recloned):
 [ * ] Waiting victim to open the link...                                    
 [ * ] Victim 0 account id: asdw password: asdwdas                           
 [ + ] saved in captured.db                                                  
                                                                             
 [ * ] Waiting for other victim to open the link...

**Comment by sky9262** [comment]
It's due to some SSL problems during handling victim/user IP info.
I also faced that and currently, I am working on it.
You'll get fixed the problem today :-)

**Comment by sky9262** [comment]
Issue fixed check now.
Let me know if you are satisfied :-)

**Comment by tuffboy807** [comment]
> Issue fixed check now. Let me know if you are satisfied :-)

Works now Appreciate the support quick fix

**Comment by sky9262** [comment]
Please make sure you have read my article for more advance phishEye.
https://sky9262.tistory.com/entry/phishEye-An-ultimate-phishing-tool#:~:text=Wanna%20go%20more%20advanced%3F
