### ISSUE TITLE
ngrok failure

### ISSUE THREAD

**Issue by muddydev** [sky9262/phishEye#2]
**Describe the bug**
Ngrok links dont work

**To Reproduce**
Run pisheye
head to any ngrokked link

**Expected behavior**
Ngrok forward to page 

**Screenshots**
![image](https://user-images.githubusercontent.com/51953831/145210275-1ef3cc60-a1f9-47ba-a0eb-24cf77fa6c8c.png)

**Additional context**
I assume its an ngrok subscription problem from usage? be good for the first to ask a question on first run what the API key is?

**Comment by sky9262** [comment]
Thanks for your issue report.
I'll fix it as soon as possible.

**Comment by sky9262** [comment]
You also can use It without ngrok.
Read this article [CLICK HERE](https://sky9262.tistory.com/entry/phishEye-An-ultimate-phishing-tool#:~:text=Wanna%20go%20more%20advanced%3F)

**Comment by sky9262** [comment]
Fixed
